---
title: "My scientific publications"
description:
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
 <body style="background-color:lightcoral;">

## Pre-print
Hashemi R, Philipps V, Jacqmin-Gadda H. Dynamic prediction of an event from multiple longitudinal markers : a model averaging approach.

Jacqmin-Gadda H, Philipps V, Tzourio C, Helmer C, Joly P. Impact of interventions scenarios targeting three main vascular risk factors on the future burden of dementia in France.

Proust-Lima C, Saulnier T, Philipps V, Pavy-Le Traon A, Peran P, Rascal O, Meissner WG, Foubert-Samier A. Describing complex disease progression using joint latent class models for multivariate longitudinal markers and clinical endpoints.


## Accepted

Saulnier T, Philipps V, Meissner WG, Rascol O, Pavy-Le Traon A, Foubert-Samier A, Proust-Lima C (2022). Joint models for the longitudinal analysis of measurement scales in the presence of informative dropout, Methods.

Proust-Lima C, Philipps V, Perrot B, Blanchin M, Sebille V (2022). Modeling repeated self-reported outcome data: a continuous-time longitudinal Item Response Theory model, Methods.

Philipps V, Hejblum BP, Prague M, Commenges D, Proust-Lima C (2021). Robust and efficient optimization using a Marquardt-Levenberg algorithm with R package marqLevAlg, R Journal.

Baussard L, Proust-Lima C, Philipps V, Portales F, Ychou M, Mazard T, Cousson-Gélie F (2021). Determinants of distinct trajectories of fatigue in patients undergoing chemotherapy for a metastatic colorectal cancer : 6-month follow-up using growth mixture modeling, J Pain Symptom Manage.

Lévêque E, Lacourt A, Philipps V, Luce D, Guénel P, Stücker I, Proust-Lima C, Leffondré K (2020). A new trajectory approach for investigating the association between an environmental or occupational exposure over lifetime and the risk of chronic disease : application to smoking, asbestos, and lung cancer, PLoS One, 15(8).

Jacqmin-Gadda H, Rouanet A, Mba RD, Philipps V, Dartigues JF (2020). Quantile regression for incomplete longitudinal data with selection by death, Stat Methods Med Res, 29(9), 2697-2716.

Carrier H, Cortaredona S, Philipps V, Jacqmin-Gadda H, Tournier M, Verdoux H, Verger P (2020). Long-term risk of hip or forearm fractures in older occasional users of benzodiazepines, Br J Clin Pharmacol, 86(11), 2155-2164.

Kwint M, Stam B, Proust-Lima C, Philipps V, Hoekstra T, Aalbersberg E, Rossi M, Sonke JJ, Belderbos J, Walraven I (2020). The prognostic value of volumetric changes of the primary tumor measured on Cone Beam-CT during radiotherapy for concurrent chemoradiation in NSCLC patients, Radiotherapy and Oncology, 146, 44-51.

Proust-Lima C, Philipps V, Dartigues JF (2019). A joint model from multiple dynamic processes and clinical endpoints : Application to Alzheimer’s disease, Stat Med, 38(23), 4702-4717.

Proust-Lima C, Philipps V, Dartigues JF, Bennett DA, Glymour MM, Jacqmin-Gadda H, Samieri C (2019). Are latent variable models preferable to composite score approaches when assessing risk factors of change? Evaluation of type-I error and statistical power in longitudinal cognitives studies, Stat Methods Med Res, 28(7), 1942-1957.

Proust-Lima C, Philipps V, Liquet B (2017). Estimation of Extended Mixed Models Using Latent Classes and Latent Processes : the R package lcmm, JSS, 78(2), 1-56.

Philipps V, Amieva H, Andrieu S, Dufouil C, Berr C, Dartigues JF, Jacqmin-Gadda H, Proust-Lima C (2014). Normalized MMSE for assessing cognitive change in population-based aging studies, NeuroEpidemiology, 43(1), 15–25.

 

